name: 'File Check Action'
description: 'An action that checks if the LICENSE and README.md files exists'
runs:
  using: 'node16'
  main: 'index.js'

inputs:
  repo-token:
    type: string
    description: "GitHub Token"
    required: true
    default: ${{github.token}}